// @ts-check
import { defineConfig } from 'astro/config';

// The XML sitemap is generated by src/pages/sitemap.xml.ts (single flat file at /sitemap.xml).

export default defineConfig({
  site: 'https://electriciantimes.com',
  trailingSlash: 'always',
  build: {
    format: 'directory',
  },
});
